name: Game Compatibility
description: Add a new game to the compatibility database
title: "<Full game name displayed in Strato>"
labels: ["triage"]
body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      description: "Search to see if an issue already exists for this game."
      options:
        - label: "I have searched the existing issues"
          required: true

  - type: input
    id: build
    attributes:
      label: "Winlator version"
      description: "Enter the Winlator version used (e.g. `Winlator Cmod 11 Beta5`)."
      placeholder: "#1337"
    validations:
      required: true

  - type: input
    id: wine
    attributes:
      label: "Wine version"
      description: "Enter the Wine version used (e.g. `Wine 9.21` or `Proton 9.2`)."
      placeholder: "Wine 9.2"
    validations:
      required: true

  - type: dropdown
    id: box
    attributes:
      label: "BOX version"
      description: "Select the BOX version used."
      options:
        - BOX64
        - BOX86
        - WOW64
        - FEXcore
      default: "BOX64"
    validations:
      required: true

  - type: dropdown
    id: preset
    attributes:
      label: "Select a preset"
      options:
        - Stability
        - Compatibility
        - Intermediate
        - Performance
        - Custom
        - FEXcore
      default: "Compatibility"

  - type: markdown
    attributes:
      value: "**If you selected 'Custom', please fill out the options below.**"

  - type: dropdown
    id: safeflags
    attributes:
      label: "SAFEFLAGS"
      options:
        - 0
        - 1
        - 2

  - type: dropdown
    id: androidversion
    attributes:
      label: "Android Version"
      options:
        - 15 Beta
        - 14
        - 13
        - 12
        - 11
        - 10
      default: "15 Beta"
    validations:
      required: true

  - type: checkboxes
    id: log_info
    attributes:
      label: "Is Log Level set to 'Info'?"
      description: "Log Level must be set to `Info` for all attached logs."
      options:
        - label: "Yes"
          required: true

  - type: textarea
    id: log
    attributes:
      label: "Log file"
      description: "Please attach a zipped emulator log file."
    validations:
      required: true
