name: Game Compatibility
description: Add a new game to the compatibility database
title: "<Full game name>"
labels: ["triage"]
body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      description: "Search to see if an issue already exists for this game."
      options:
        - label: "I have searched the existing issues"
          required: true

  - type: markdown
    attributes:
      value: "# **WINLATOR SETTINGS**"


  - type: input
    id: build
    attributes:
      label: "Winlator version"
      description: "Enter the Winlator version used (e.g. `Winlator Cmod 11 Beta5`)."
      placeholder: "Winlator Frost, Afei, Cmod etc.."
    validations:
      required: true

  - type: input
    id: wine
    attributes:
      label: "Wine version"
      description: "Enter the Wine version used (e.g. `Wine 9.21` or `Proton 9.2`)."
      placeholder: "Wine 9.2"
    validations:
      required: true

  - type: dropdown
    id: box
    attributes:
      label: "BOX version"
      description: "Select the BOX version used."
      options:
        - BOX64
        - BOX86
        - WOW64
        - FEXcore
      default: 0  # First item in the list is selected by default
    validations:
      required: true


  - type: markdown
    attributes:
      value: "# **PRESET SETTINGS**"


  - type: dropdown
    id: preset
    attributes:
      label: "Select a preset"
      options:
        - Stability
        - Compatibility
        - Intermediate
        - Performance
        - Custom
        - FEXcore
      default: 1  # "Compatibility" is the second item, so index = 1

  - type: markdown
    attributes:
      value: "**IF YOU SELECTED 'CUSTOM', PLEASE FILL OUT THE OPTIONS BELOW.**"

  - type: dropdown
    id: safeflags
    attributes:
      label: "SAFEFLAGS"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected

  - type: dropdown
    id: bigblock
    attributes:
      label: "BIGBLOCK"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: strongmem
    attributes:
      label: "STRONGMEM"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: fastnan
    attributes:
      label: "FASTNAN"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: fastround
    attributes:
      label: "FASTROUND"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: x87double
    attributes:
      label: "X87DOUBLE"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: forward
    attributes:
      label: "DYNAREC FORWARD"
      options:
        - 0
        - 128
        - 256
        - 512
        - 1024
      default: 3  # Fourth option selected

  - type: dropdown
    id: callret
    attributes:
      label: "CALLRET"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: wait
    attributes:
      label: "WAIT"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected


  - type: dropdown
    id: avx
    attributes:
      label: "AVX"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected


  - type: dropdown
    id: weakbarrier
    attributes:
      label: "WEAKBARRIER"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected



      

  - type: dropdown
    id: androidversion
    attributes:
      label: "Android Version"
      options:
        - 15 Beta
        - 14
        - 13
        - 12
        - 11
        - 10
      default: 0  # "15 Beta" is the first item, so index = 0
    validations:
      required: true

  - type: checkboxes
    id: log_info
    attributes:
      label: "Is Log Level set to 'Info'?"
      description: "Log Level must be set to `Info` for all attached logs."
      options:
        - label: "Yes"
          required: true

  - type: textarea
    id: log
    attributes:
      label: "Log file"
      description: "Please attach a zipped emulator log file."
    validations:
      required: true
