name: Game Compatibility
description: Add a new game to the compatibility database
title: "<Full game name>"
labels: ["triage"]
body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      description: "Search to see if an issue already exists for this game on the same soc and winlator version."
      options:
        - label: "I have searched the existing issues"
          required: true


  - type: input
    id: build
    attributes:
      label: "Winlator version"
      description: "Enter the Winlator version used (e.g. `Winlator Cmod 11 Beta5`)."
      placeholder: "Winlator 9, 10, Cmod, Afei etc.."
    validations:
      required: true


  - type: markdown
    attributes:
      value: "# **WINLATOR SETTINGS**"

  - type: input
    id: wine
    attributes:
      label: "Wine version"
      description: "Enter the Wine version used (e.g. `Wine 9.21` or `Proton 9.2`)."
      placeholder: "Wine 9.2"
    validations:
      required: true

  - type: input
    id: box
    attributes:
      label: "BOX version"
      description: "Enter the BOX version used (e.g. `BOX64 0.3.5` or `BOX32`)."
      placeholder: "BOX64 0.3.5"
    validations:
      required: true
  - type: input
    id: box_commit_id
    attributes:
      label: "Commit id"
      description: "OPTIONAL: Enter the commit id (e.g. `6c46e3d-1`)."
      placeholder: "xxxxxxx"


  - type: markdown
    attributes:
      value: "# **PRESET SETTINGS**"


  - type: dropdown
    id: preset
    attributes:
      label: "Preset"
      options:
        - Stability
        - Compatibility
        - Intermediate
        - Performance
        - Custom
        - FEXcore
      default: 1  # "Compatibility" is the second item, so index = 1

  - type: markdown
    attributes:
      value: "**IF YOU SELECTED 'FEXcore', PLEASE FILL OUT THE OPTIONS BELOW, ELSE SKIP.**"

  - type: dropdown
    id: tsomode
    attributes:
      label: "TSOMode"
      options:
        - DISABLED
        - FASTEST
        - FAST
        - SLOW
      default: 0  # First option selected

  - type: dropdown
    id: x87mode
    attributes:
      label: "X87Mode"
      options:
        - FAST
        - SLOW
      default: 0  # First option selected

  - type: dropdown
    id: multiblock
    attributes:
      label: "Multiblock"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected
      


  - type: markdown
    attributes:
      value: "**IF YOU SELECTED 'CUSTOM', PLEASE FILL OUT THE OPTIONS BELOW.**"

  - type: dropdown
    id: safeflags
    attributes:
      label: "SAFEFLAGS"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected

  - type: dropdown
    id: bigblock
    attributes:
      label: "BIGBLOCK"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: strongmem
    attributes:
      label: "STRONGMEM"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: fastnan
    attributes:
      label: "FASTNAN"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: fastround
    attributes:
      label: "FASTROUND"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: x87double
    attributes:
      label: "X87DOUBLE"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: forward
    attributes:
      label: "DYNAREC FORWARD"
      options:
        - 0
        - 128
        - 256
        - 512
        - 1024
      default: 3  # Fourth option selected

  - type: dropdown
    id: callret
    attributes:
      label: "CALLRET"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: wait
    attributes:
      label: "WAIT"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected


  - type: dropdown
    id: avx
    attributes:
      label: "AVX"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected


  - type: dropdown
    id: weakbarrier
    attributes:
      label: "WEAKBARRIER"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected


  - type: markdown
    attributes:
      value: "# **CONTAINER/SHORTCUT SETTINGS**"

  - type: checkboxes
    id: bionic
    attributes:
      label: "BIONIC CONTAINER?"
      description: "If this is a Bionic container, check this."
      options:
        - label: "This is a Bionic container."

  - type: dropdown
    id: graphics_driver
    attributes:
      label: "Graphics Drivers"
      description: "Do not select `Wrapper` if the container is not Bionic."
      options:
        - Turnip
        - VirGL
        - Wrapper
      default: 0  # First option selected
  - type: input
    id: graphics_driver_input
    attributes:
      label: "Driver Version"
      description: "Enter the version used (e.g. `turnip v25.1.0-R6`)."
      placeholder: "System Driver"
    validations:
      required: true

  - type: dropdown
    id: dx_wrapper
    attributes:
      label: "DX Wrapper"
      options:
        - WineD3D
        - DXVK
        - VKD3D
        - CNC DDraw
      default: 0  # First option selected

  - type: input
    id: dx_wrapper_input
    attributes:
      label: "Wrapper Version"
      description: "Enter the version used (e.g. `DXVK 2.6.1`)."
      placeholder: "DXVK 1.10.3"
    validations:
      required: true

  - type: dropdown
    id: audio
    attributes:
      label: "Audio Driver"
      options:
        - ALSA
        - PulseAudio
      default: 0  # First option selected

  - type: dropdown
    id: services
    attributes:
      label: "Startup Selection"
      options:
        - Normal
        - Essential
        - Aggressive
      default: 0  # First option selected


  - type: dropdown
    id: socvendor
    attributes:
      label: SoC type
      options:
      - Snapdragon
      - Mediatek
      - Exynos
      - Kirin
      - Tegra
      - UNISOC
      - Other
    validations:
      required: true


  - type: dropdown
    id: androidversion
    attributes:
      label: "Android Version"
      options:
        - 15 Beta
        - 14
        - 13
        - 12
        - 11
        - 10
      default: 0  # "15 Beta" is the first item, so index = 0
    validations:
      required: true

  - type: checkboxes
    id: log_info
    attributes:
      label: "Confirm `Debug` and `BOX86/BOX64` logging is enabled."
      description: "For posting logs make sure these are enabled."
      options:
        - label: "Yes"

  - type: textarea
    id: log
    attributes:
      label: "Behavior, Extra information, pics, vids, log file and RC file"
      description: "Add any extra information, such as dependencies, footage, pictures RC files..."
    validations:
      required: true
