name: GLIBC/Proot Compatibility
description: Add a new game to the compatibility database
title: "<Full game name>"
labels: ["triage"]
body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      description: "Search to see if an issue already exists for this game on the same soc and winlator version."
      options:
        - label: "I have searched the existing issues"
          required: true


  - type: input
    id: build
    attributes:
      label: "Winlator version"
      description: "Enter the Winlator version used (e.g. `Winlator Cmod 11 Beta5`)."
      placeholder: "Winlator 9, 10, Cmod, Afei etc.."
    validations:
      required: true


  - type: markdown
    attributes:
      value: "# **WINLATOR SETTINGS**"

  - type: input
    id: wine
    attributes:
      label: "Wine version"
      description: "Enter the Wine version used (e.g. `Wine 9.21` or `Proton 9.2`)."
      placeholder: "Wine 9.2"
    validations:
      required: true

  - type: input
    id: box
    attributes:
      label: "BOX version"
      description: "Enter the BOX version used (e.g. `BOX64 0.3.5` or `BOX32`)."
      placeholder: "BOX64 0.3.5"
    validations:
      required: true
  - type: input
    id: box_commit_id
    attributes:
      label: "Commit id"
      description: "OPTIONAL: Enter the commit id (e.g. `6c46e3d-1`)."
      placeholder: "xxxxxxx"


  - type: markdown
    attributes:
      value: "# **PRESET SETTINGS**"


  - type: dropdown
    id: preset
    attributes:
      label: "Preset"
      options:
        - Stability
        - Compatibility
        - Intermediate
        - Performance
        - Custom
        - FEXcore
      default: 1  # "Compatibility" is the second item, so index = 1
      

  - type: markdown
    attributes:
      value: "**IF YOU SELECTED 'CUSTOM', PLEASE FILL OUT THE OPTIONS BELOW.**"

  - type: dropdown
    id: safeflags
    attributes:
      label: "SAFEFLAGS"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected

  - type: dropdown
    id: bigblock
    attributes:
      label: "BIGBLOCK"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: strongmem
    attributes:
      label: "STRONGMEM"
      options:
        - 0
        - 1
        - 2
        - 3
      default: 0  # First option selected

  - type: dropdown
    id: fastnan
    attributes:
      label: "FASTNAN"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: fastround
    attributes:
      label: "FASTROUND"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: x87double
    attributes:
      label: "X87DOUBLE"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: forward
    attributes:
      label: "DYNAREC FORWARD"
      options:
        - 0
        - 128
        - 256
        - 512
        - 1024
      default: 3  # Fourth option selected

  - type: dropdown
    id: callret
    attributes:
      label: "CALLRET"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected

  - type: dropdown
    id: wait
    attributes:
      label: "WAIT"
      options:
        - DISABLED
        - ENABLED
      default: 0  # First option selected


  - type: dropdown
    id: avx
    attributes:
      label: "AVX"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected


  - type: dropdown
    id: weakbarrier
    attributes:
      label: "WEAKBARRIER"
      options:
        - 0
        - 1
        - 2
      default: 0  # First option selected


  - type: markdown
    attributes:
      value: "# **CONTAINER/SHORTCUT SETTINGS**"

  - type: input
    id: resolution
    attributes:
      label: "Resolution"
      description: "Enter the resolution used (e.g. `720p`, `1080p`..)."
      placeholder: "720p"
    validations:
      required: true

  - type: dropdown
    id: graphics_driver
    attributes:
      label: "Graphics Drivers"
      options:
        - Turnip
        - VirGL
        - Wrapper
        - Vortek
      default: 0  # First option selected
  - type: input
    id: graphics_driver_input
    attributes:
      label: "Driver Version"
      description: "Enter the version used (e.g. `turnip v25.1.0-R6`)."
      placeholder: "System Driver"
    validations:
      required: true

  - type: dropdown
    id: dx_wrapper
    attributes:
      label: "DX Wrapper"
      options:
        - WineD3D
        - DXVK
        - VKD3D
        - CNC DDraw
      default: 0  # First option selected

  - type: input
    id: dx_wrapper_input
    attributes:
      label: "Wrapper Version"
      description: "Enter the version used (e.g. `DXVK 2.6.1`)."
      placeholder: "DXVK 1.10.3"
    validations:
      required: true

  - type: dropdown
    id: audio
    attributes:
      label: "Audio Driver"
      options:
        - ALSA
        - PulseAudio
      default: 0  # First option selected

  - type: dropdown
    id: services
    attributes:
      label: "Startup Selection"
      description: "The mode for Services on startup."
      options:
        - Normal
        - Essential
        - Aggressive
      default: 0  # First option selected


  - type: dropdown
    id: socvendor
    attributes:
      label: SoC
      options:
      - 8 Elite
      - 8 Gen3
      - G3X Gen2
      - 8 Gen2
      - 8 Gen1
      - SD888
      - SD870
      - SD865
    validations:
      required: true


  - type: dropdown
    id: androidversion
    attributes:
      label: "Android Version"
      options:
        - 15 Beta
        - 14
        - 13
        - 12
        - 11
        - 10
      default: 0  # "15 Beta" is the first item, so index = 0
    validations:
      required: true

  - type: checkboxes
    id: log_info
    attributes:
      label: "Confirm `Debug` and `BOX86/BOX64` logging is enabled."
      description: "For posting logs make sure these are enabled."
      options:
        - label: "Yes"

  - type: textarea
    id: log
    attributes:
      label: "Behavior, Extra information and file attachments"
      description: "Add any extra information, such as dependencies, footage, pictures and optionally RC files and log files..."
    validations:
      required: true
